
version: '3.9'

services:

    jupyter:
        build: .
        image: machine-learning-jupyterlab-docker
        user: root
        ports:
            - 8888:8888
        volumes:
            - ./project:/project
        command: jupyter lab --ip=0.0.0.0 --port=8888 --allow-root
                    

